name: "Secret Scan fork"
description: "Scan your repository for secrets with TruffleHog"
author: "channelbeta"
inputs:
  include_path:
    description: 'Path to the configuration file with include path patterns'
    required: false
  exclude_path:
    description: 'Path to the configuration file with exclude path patterns'
    required: false
  allowed_patterns:
    description: 'Path to the configuration file with allowed patterns'
    required: false
runs:
  using: "docker"
  image: "docker://ghcr.io/channelbeta/secret-scan:2.1.6"
  args:
    - ${{ inputs.include_path }}
    - ${{ inputs.exclude_path }}
    - ${{ inputs.allowed_patterns }}
branding:
  icon: lock
  color: purple
